### ISSUE TITLE
Mame Redump: "System settings" are being ignored - UI is not naming the system config files correctly

### ISSUE THREAD

**Issue by Daeymon** [unexpectedpanda/retool#306] opened 2024-02-20 05:51 UTC
I know this will be related to my other issue, where the `<Machine>` option is not working unless set globally. But I now realise that the "System settings" overrides are being completely ignored when processing any Mame Redump dats. On various systems I have system specific region orders and overrides, and none of those are being applied. It's processing the data strictly on the global options.

I did a bit of playing, and the issue seems to be that when dealing with the CHD dats, the UI creates a brand new system config file that does not have " (Redump)" in its name, and that is where all the choices made in the UI are saved. But I believe the actual process is still trying to read a file with "(Redump)" in the name. I checked this by copying the config file generated by the UI, adding " (Redump)" to the filename, and re-processed the dat. All the system overrides were correctly applied.

**Comment by unexpectedpanda** [comment] 2024-02-20 06:12
Duplicate of #305, for the reasons laid out there.

**Closed by unexpectedpanda** 2024-02-20 06:12 UTC
