### ISSUE TITLE
Lower revision multi-region titles being selected over higher revision individual region titles

### ISSUE THREAD

**Issue by Daeymon** [unexpectedpanda/retool#292] opened 2023-12-04 23:54 UTC
For the GBC NoIntro dat (Nintendo - Game Boy Color (Parent-Clone) (20231203-225121))

Super Mario Bros. Deluxe (USA, Europe) (Rev 1).zip

is being chosen instead of

Super Mario Bros. Deluxe (Europe) (Rev 2).zip

Region Priority is: World, UK, Europe, USA, Canada, Australia, New Zealand.
No Title Options are enabled.
Using version 2.01.7

In all the examples I am seeing this, the prioritised file is multi-region. Maybe that is affecting the grouping when determining which is the best revision?

**Comment by unexpectedpanda** [comment] 2023-12-05 01:03
This isn't a bug, but by design. And yes, multi-region is prioritized.

Revisions should be thought of as unique to their regions, as the code for each region can be different (whether that be 60/50Hz related, different languages supported, censorship, or otherwise).

A rev 1 from Europe for example doesn't necessarily include the same code changes as a rev 1 from the USA. One region might have required fixes that the other did not.

Retool treats (USA, Europe) as different to (Europe) when it comes to revisions for this reason. By covering multiple regions, the code is likely different to the releases that only cover one.

A note on the revision numbers themselves &mdash; often they're copied directly from the cartridge to the filename. In this instance, it's likely that _Super Mario Bros. Deluxe (Europe) (Rev 2)_ isn't a revision on _Super Mario Bros. Deluxe (USA, Europe) (Rev 1)_ at all. It's just that _Super Mario Bros. Deluxe (Europe) (Rev 1)_ hasn't been dumped, or never saw release.

**Comment by Daeymon** [comment] 2023-12-05 12:32
Fully appreciate you having a deeper look into this. Though I have found another example that throws a stone into the logic you stated where multi-regions have more priority.

With "Sega - Game Gear (Parent-Clone) (20231124-140549)"

"PGA Tour Golf (USA) (Rev 1)" was priortised over "PGA Tour Golf (USA, Europe)".

Same region order as before. Does this mean the USA region is priortised over multi-region in this instance? Especially when I ordered USA below Europe in terms of region priorities.

**Comment by unexpectedpanda** [comment] 2023-12-10 04:42
This took a bit of testing and teasing out, but you should find the title selection is much better in v2.01.8 as far as multi-region titles are concerned.

The short version is: multi-region titles are still assigned to a single region for initial comparison, but they're assigned to the region higher up in the user's region order rather than to something fixed. So something with `(USA, Europe)` is no longer permanently assigned to `USA` -- if `Europe` is higher in your region order than `USA`, it'll be assigned to `Europe` instead.

There were benefits here beyond getting the highest European revision -- Retool's also making smarter choices now for compilations versus individual titles for those who put Europe higher than USA in the list.

Thanks for raising this, and really appreciate you sticking with it when I got things wrong.

**Closed by unexpectedpanda** 2023-12-10 04:42 UTC
Labels: bug
