### ISSUE TITLE
Nintendo DS corrections.

### ISSUE THREAD

**Issue by TomTurbine** [unexpectedpanda/retool#328] opened 2024-04-22 20:36 UTC
1)Hello again, hope it is all going well. Was messing around with the DS collection and noticed a few things.

Here are some stuff that should be filtered out as programs. I am also going to submit them to No-Intro to correctly add the [Program] tag for them.

AceKard 2 (World) (v2.1) (Unl)
AceKard 2i (World) (Unl)
AceKard R.P.G. (World) (Unl)
Action Replay DS (World) (v1.02) (Unl)
Cartridge Construction Kit (World) (v1.22) (Unl)
CodeBreaker DS Lite (World) (Unl)
CycloDS Evolution (World) (v1.1) (Unl)
Data Max (World) (Unl)
DSTT (World) (Unl)
DSTTi (World) (Unl)
EDGE (World) (Unl)
EZ-Flash V (World) (Unl)
EZ-Flash Vi (World) (Unl)
G6DS Real (World) (Unl)
iTouch DS (World) (Unl)
M3DS Real (World) (Unl)
M3DS Simply & R4DS (World) (Unl)
Max Media Launcher (World) (Unl)
Max Media Player (World) (v1.22) (Unl)
Nintendo DS Browser (USA, Europe) (En,Fr,De,Es,It)
Nintendo Zone Wireless Distribution Box DS Card (World) (Rev 1)
Passcard 3 (World) (v6.0) (Unl)
R4i Ultra (World) (Unl)
Relay Station (USA)
Super Key (World) (v6.0) (Unl)
SuperCard DSONE (SDHC) (World) (Unl)
SuperCard DSTWO (World) (Unl)

2)With the 2 games
Beyblade - Metal Fusion (USA) (En,Fr,Es)
Beyblade - Metal Masters (USA) (En,Fr,Es)

They have multiple versions. I am not 100% sure but I believe you might want to keep the "Collector's Edition" of each of them instead of the default.

3)And the game
Little League World Series Baseball - Double Play (USA)

is a compilation of 
Little League World Series Baseball 2008 (USA)
Little League World Series Baseball 2009 (USA)

**Comment by TomTurbine** [comment] 2024-04-22 20:51
And with DSi

Nintendo DSi XL Demo Video (USA)
Nintendo DSi XL Demo Video Volume 2 (USA)

I would think would be filtered out as either a demo or a video.

**Comment by TomTurbine** [comment] 2024-04-22 21:32
Edit: And for 3DS
Nintendo Fan Network (USA) (Rev 1)
Nintendo DSi Sound (USA) (Rev 2)
Nintendo DSi Shop (USA) (Rev 12)
Nintendo DSi Metronome (USA)
Nintendo DSi Camera (USA) (Rev 4)
Nintendo DSi Browser (USA) (Rev 3)
Nintendo DSi + Internet (USA) (Pre-install)
Nintendo DSi - Instrument Tuner (USA)
Nintendo Countdown Calendar (USA)
Nintendo 3DS Transfer Tool (USA) (Rev 1)

**Comment by TomTurbine** [comment] 2024-04-22 23:03
Messed around with the CDN content, I think I have noticed something.

I noticed that if you have 2 copies of a game and if the first one has something like (En,De,Es) at the end of it, it wants to prioritize it over the next one that has (Rev 1) but doesn't also have the language list in the name.

**Comment by TomTurbine** [comment] 2024-04-23 01:23
Also, for my settings.

For Regions I have USA>World>Unknown and that's it.
For Languages, I have English only.

Exclusions:
Applications
Bad Dumps
BIOS and other chips
Demos, kiosks, and samples
Preproduction
Promotional
Aftermarket
Pirate


The rest is all default.

**Comment by unexpectedpanda** [comment] 2024-04-24 10:21
> I noticed that if you have 2 copies of a game and if the first one has something like (En,De,Es) at the end of it, it wants to prioritize it over the next one that has (Rev 1) but doesn't also have the language list in the name.
>
> Example:
>
> GameA (En,De,Es).7z
> GameA (Rev 1).7z
>
> It would take the first one while ignoring the fact it had a newer revision.

Working as intended. If there are missing languages it needs to be fixed at the source. I'll be able to get to the others in the next clone list update.

**Comment by DubaiShark** [comment] 2024-04-28 01:35
Hi Thanks for the update it's great and helpful 
I have the same issue here but with "Unofficial - Sony - PlayStation Portable (PSN) (Decrypted) (Parent-Clone) (20230704-163013).dat" and "Mattel - Intellivision (Parent-Clone) (20231027-021641).dat" and maybe others

the problem is it grabs the same games for 2 or 3 games with different regions at the same time :\ it will be great if this will be solved

Thanks for your support

**Comment by unexpectedpanda** [comment] 2024-04-28 01:58
> Hi Thanks for the update it's great and helpful I have the same issue here but with "Unofficial - Sony - PlayStation Portable (PSN) (Decrypted) (Parent-Clone) (20230704-163013).dat" and "Mattel - Intellivision (Parent-Clone) (20231027-021641).dat" and maybe others
> 
> the problem is it grabs the same games for 2 or 3 games with different regions at the same time :\ it will be great if this will be solved
> 
> Thanks for your support

I don't know that this means. Examples are helpful.

**Comment by DubaiShark** [comment] 2024-04-28 03:04
OK here are the  pictures that will explain the issue 

![1](https://github.com/unexpectedpanda/retool/assets/115087432/684ae5be-66de-40ab-84db-be5d7c3e2e8a)

My filter was like this and it works fine for other .data

![2](https://github.com/unexpectedpanda/retool/assets/115087432/49ddf05c-bd19-4352-a0cd-06395f8b6de0)

![3](https://github.com/unexpectedpanda/retool/assets/115087432/6f529ea7-265e-4d35-a18f-7b4991a02457)

I don't know if the retool program will update the clon list for this data or not or if it is a bug in the program this only happens with Unofficial - Sony - PlayStation Portable (PSN) (Decrypted) and Mattel - Intellivision (Parent-Clone) for now 

I hope it's clear now

Thanks

**Comment by unexpectedpanda** [comment] 2024-04-28 03:37
> 2)With the 2 games
> Beyblade - Metal Fusion (USA) (En,Fr,Es)
> Beyblade - Metal Masters (USA) (En,Fr,Es)

> They have multiple versions. I am not 100% sure but I believe you might want to keep the "Collector's Edition" of each of them > instead of the default.

This one isn't fun. Each of the collector/Toys'R'Us/Target/Best Buy/Walmart come with unique "Beys", there isn't an everything collection.

[Beyblade - Metal Fusion](https://beyblade.fandom.com/wiki/Beyblade:_Metal_Fusion_(video_game))
[Beyblade - Metal Masters](https://beyblade.fandom.com/wiki/Beyblade:_Metal_Masters_(video_game))

In theory I should care about the unique content... but the functionality doesn't exist to cater for it at the moment. I'll make a small adjustment so at least one of the special editions is selected in the meantime.

**Comment by unexpectedpanda** [comment] 2024-04-28 03:44
> Unofficial - Sony - PlayStation Portable (PSN) (Decrypted)

Thanks. There is no clone list for `Unofficial - Sony - PlayStation Portable (PSN) (Decrypted)`, so you will get clones in that DAT file where the names don't match up in a way that they can be automatically detected. I'll leave the clone list up to someone else to create.

> (Parent-Clone)

Don't use parent/clone DAT files for Retool, use the regular ones. Additionally, the clone list for Intellivision needs an update.

**Comment by unexpectedpanda** [comment] 2024-04-28 04:08
> Nintendo Fan Network (USA) (Rev 1)
> Nintendo DSi Sound (USA) (Rev 2)
> Nintendo DSi Shop (USA) (Rev 12)
> Nintendo DSi Metronome (USA)
> Nintendo DSi Camera (USA) (Rev 4)
> Nintendo DSi Browser (USA) (Rev 3)
> Nintendo DSi + Internet (USA) (Pre-install)
> Nintendo DSi - Instrument Tuner (USA)
> Nintendo Countdown Calendar (USA)
> Nintendo 3DS Transfer Tool (USA) (Rev 1)

There is no DSi digital clone list. I'll leave this up to someone else to create.

The other changes have been made.

**Comment by DubaiShark** [comment] 2024-04-28 04:08
> Don't use parent/clone DAT files for Retool, use the regular ones. Additionally, the clone list for Intellivision needs an update.

Is there a difference or is it not working? I used this one and it seems it gives me the correct 1G1R each time for the other DATA 

So now I have to download the regular one and use it rather than (Parent-Clone) right

**Comment by unexpectedpanda** [comment] 2024-04-28 04:13
> Is there a difference or is it not working? 

For Intellivision, no, there's no difference. It's just that Retool ignores the clone data in No-Intro's P/C DAT files. Dat-O-Matic also provides more customization options for the regular file.

I've heard others say that things get out of sync and that regular DAT files have content in it that parent/clone DATs don't, but I've never verified.

**Comment by unexpectedpanda** [comment] 2024-04-28 04:14
Okay, all this have been addressed, so closing now.

**Closed by unexpectedpanda** 2024-04-28 04:14 UTC
Labels: Incorrect parent/clone relationship
