### ISSUE TITLE
Bug with latest No-Intro datfiles

### ISSUE THREAD

**Issue by Jaylinx** [unexpectedpanda/retool#195] opened 2022-05-11 08:50 UTC
Latest datfiles from No-Intro crashes on Retool, NES, Genesis, N64 and several others. I don't know if they changed something in their process.

It crashes on individual selection and I have this error message on folder selection

* Error: XML file doesn't conform to Logiqx dtd.
  <string>:4094:0:ERROR:VALID:DTD_UNKNOWN_ATTRIBUTE: No declaration for
  attribute sha256 of element rom. Skipping file...

**Comment by unexpectedpanda** [comment] 2022-05-11 13:18
Just No-Intro breaking their DTD again by introducing SHA256 hashes. I'll patch things when the opportunity arises, but it means I also need to add the new hashes to the output DAT.

**Comment by unexpectedpanda** [comment] 2022-05-11 21:53
This should be fixed in [1.08](https://github.com/unexpectedpanda/retool/releases/tag/v1.08).

**Comment by Jaylinx** [comment] 2022-05-12 06:55
Great, thanks !

**Comment by Jaylinx** [comment] 2022-05-16 10:53
New bug with latest NES datfile

* Error: XML file doesn't conform to Logiqx dtd.
  <string>:13223:0:ERROR:VALID:DTD_UNKNOWN_ATTRIBUTE: No declaration for
  attribute header of element rom. Skipping file...

**Comment by unexpectedpanda** [comment] 2022-05-17 03:12
Not a bug, that's No-Intro violating its own standards yet again and so failing the DTD check.

The introduction of headered DATs has been a little chaotic, much like the `nodump` experience a little while back. I wouldn't be surprised if this took a little while to stabilize. Kind of surprised they put it as an attribute on the `rom` element, and didn't introduce a `header` element, which would have been a more scalable option.

Come Retool 2.0 there'll be an option to skip the DTD check. DTDs are meant to keep things predictable, but if No-Intro keeps breaking things 🤷

**Comment by unexpectedpanda** [comment] 2022-05-17 03:43
Fixed in 1.09.

**Closed by unexpectedpanda** 2022-05-17 03:43 UTC
Labels: enhancement
