### ISSUE TITLE
Saturn name matching

### ISSUE THREAD

**Issue by Uplinkpro** [unexpectedpanda/retool#33] opened 2021-02-17 22:46 UTC
## Dat
The dat name where the issue is.
Sega - Saturn - Datfile (2329) (2021-01-27 01-30-37)

## Issue
Where possible, include URLs to a reputable source as proof, as it helps speed up verification.

Almost 300 + renames but a good chunk of them are completely mismatched

* Missed or incorrect title (Europe) > Original title (USA) | https://www.wikipedia.org

wrong name: Z:\ReDump Raw\Area 51 (Japan).zip [wrong: Z:\ReDump Raw\Area 51 (Japan)] [right: Gungriffon (USA)]
wrong name: Z:\ReDump Raw\Alien Trilogy (Europe) (En,Fr,Es,It) (7S).zip [wrong: Z:\ReDump Raw\Alien Trilogy (Europe) (En,Fr,Es,It) (7S)] [right: Bubble Bobble also featuring Rainbow Islands (USA)]

**Comment by unexpectedpanda** [comment] 2021-02-18 07:13
If I'm understanding correctly, it looks like you're running a scan on an existing set using CLRMAMEPro, with a region priority where USA is above Europe.

CLRMAMEPro gives misleading messages when it scans existing non-1G1R Redump sets with a Retool dat, and finds identical files that were shared between titles in the original Redump dat. This generally only happens with dats that contain multitrack discs (cue/bin) like Saturn or Mega CD, where it's common to find the same file across multiple unrelated titles.

Take _Area 51 (Japan)_ and _Gungriffon (USA)_ from the original Redump Saturn dat for example (truncated to highlight relevant data):

<pre>
&lt;game name="Area 51 (Japan)"&gt;
	&lt;category>Games&lt;/category&gt;
	&lt;description>Area 51 (Japan)&lt;/description&gt;
	...
	<strong>&lt;rom name="Area 51 (Japan) (Track 2).bin" size="1413552" crc="5af76f8c" md5="5fedd4a8361a9c6ca005b5d48a38ca68" sha1="db9145b3f24a83bcb28a93889001c778d7ab656a"/&gt;</strong>
&lt;/game&gt;
</pre>

<pre>
&lt;game name="Gungriffon (USA)"&gt;
	&lt;category>Games&lt;/category&gt;
	&lt;description>Gungriffon (USA)&lt;/description&gt;
	...
	<strong>&lt;rom name="Gungriffon (USA) (Track 33).bin" size="1413552" crc="5af76f8c" md5="5fedd4a8361a9c6ca005b5d48a38ca68" sha1="db9145b3f24a83bcb28a93889001c778d7ab656a"/&gt;</strong>
	...
&lt;/game&gt;
</pre>

`Area 51 (Japan) (Track 2).bin` is the exact same file as `Gungriffon (USA) (Track 33).bin`, with matching sizes and checksums (crc/md5/sha1). When you use the Retool dat (which has removed _Area 51 (Japan)_ as a dupe of _Area 51 (USA)_) and CLRMAMEPro says the following:

> wrong name: Z:\ReDump Raw\Area 51 (Japan).zip [wrong: Z:\ReDump Raw\Area 51 (Japan)] [right: Gungriffon (USA)]

It doesn't mean "hey, _Area 51 (Japan)_ **is** _GunGriffon (USA)_", which as you've pointed out isn't correct. What it means is:

1. I found a file called `Area 51 (Japan).zip`, and the contents as a whole don't match any set listed in the current dat.
1. I did find a file inside the zip though that matches a file in the _GunGriffon (USA)_ set, which _is_ in the dat.
1. I want to get that file into a _GunGriffon_ zip if it needs it, then remove the remaining uneeded files.

This particular file is also in _Maximum Force (Europe)_, _Maximum Force (USA)_, _GunGriffon (Europe)_ (multiple times), _Area 51 (Europe) (En,Fr,De,Es)_, _House of the Dead, The (Japan) (Demo)_, and _Area 51 (USA)_, but the European and Japanese titles have presumably been removed from the dat by Retool, and CLRMAMEPro's algorithm has decided it's going to look at _GunGriffon (USA)_ first.

Same thing with your other example, it's finding two ROMs that are identical within the titles:

<pre>
&lt;game name="Alien Trilogy (Europe) (En,Fr,Es,It) (7S)"&gt;
	&lt;category>Games&lt;/category&gt;
	&lt;description>Alien Trilogy (Europe) (En,Fr,Es,It) (7S)&lt;/description&gt;
	...
	<strong>&lt;rom name="Alien Trilogy (Europe) (En,Fr,Es,It) (7S) (Track 14).bin" size="32163600" crc="a474bd34" md5="c518a6fdff747c98cc05b0004c043934" sha1="a6f3b0a17fe9af97df91af2dbb3f9379595605d2"/&gt;</strong>
&lt;/game&gt;
</pre>

<pre>
&lt;game name="Bubble Bobble also featuring Rainbow Islands (USA)"&gt;
	&lt;category&gt;Games&lt;/category&gt;
	&lt;description&gt;Bubble Bobble also featuring Rainbow Islands (USA)&lt;/description&gt;
	...
	<strong>&lt;rom name="Bubble Bobble also featuring Rainbow Islands (USA) (Track 2).bin" size="32163600" crc="a474bd34" md5="c518a6fdff747c98cc05b0004c043934" sha1="a6f3b0a17fe9af97df91af2dbb3f9379595605d2"/&gt;</strong>
&lt;/game&gt;
</pre>

If you let CLRMAMEPro do its thing and say yes to everything, you'll end up with a set that's fine by the end. If you're unsure and worried about affecting a current set, there's another way you can verify things are working just fine:

1. Point the Retool dat in CLRMAMEPro at a new ROM path that's an empty folder.
2. Set your original folder with the existing Redump set in it as an Add path.
3. Use the rebuilder function to create the 1G1R set (making sure to select **Use Add-Paths**).
4. (Optional) Scan the new 1G1R set with the original Redump dat to verify that everything is indeed good.

I'll make sure to add this to the documentation in the future so people are aware of this quirk, along with the note that sometimes CLRMAMEPro gets a bit confused and [doesn't delete files that it should](https://github.com/unexpectedpanda/retool/issues/30).

If you continue to see problems, drop an extra note here and I'll do my best to help.

**Closed** 2021-02-18 09:20 UTC
Labels: CLRMAMEPro issue
