### ISSUE TITLE
Issue scanning NoIntro DAT in v2.00.5

### ISSUE THREAD

**Issue by muggsyd** [unexpectedpanda/retool#264] opened 2023-06-01 01:51 UTC
**Describe the bug**
When processing all my DATs via retool cli I get an error processing "Nintendo - Game Boy Advance (Multiboot)" using 2.00.5 (works correctly using 2.00.3). Error shown below

retool-testing  | * Reading DAT file: "/retool/dats/NoIntro/Nintendo - Game Boy Advance (Multiboot)
retool-testing  |   (20220808-164416).dat"
retool-testing  | * Validating DAT file... done.
retool-testing  |
retool-testing  | |  DAT DETAILS
retool-testing  | |  Description: Nintendo - Game Boy Advance (Multiboot)
retool-testing  | |  Author/s: Arctic Circle System, C. V. Reynolds, chillerecke, DeriLoko3, Hiccup, hking0036,
retool-testing  |    niemand, norkmetnoil577, omonim2007, relax
retool-testing  | |  URL: https://www.no-intro.org
retool-testing  | |  Version: 20220808-164416
retool-testing  | |  Numbered dat: No
retool-testing  |
* Processing DAT file... done
retool-testing  | * Analyzing clone list variants... done.
retool-testing  | * Applying category and user excludes...
retool-testing  |
retool-testing  | * Unexpected error:
retool-testing  |
retool-testing  |
retool-testing  | Traceback (most recent call last):
retool-testing  |   File "/retool/retool.py", line 297, in <module>
retool-testing  |     main()
retool-testing  |   File "/retool/retool.py", line 201, in main
retool-testing  |     processed_titles = IncludeExcludeTools.excludes(processed_titles, config, removes)
retool-testing  |   File "/retool/modules/titletools.py", line 186, in excludes
retool-testing  |     category_remove_name: str = f'{category.lower()}_removes'.replace(' ' , '_').replace('-', '_')
retool-testing  | UnboundLocalError: local variable 'category' referenced before assignment
retool-testing  |
retool-testing  |

**To reproduce**
run retool.py against DAT using these switches --exclude aAbBcdDemMopPrv

**Expected behavior**

**Operating system**
- [ ] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [X] Debian via Docker

**Retool edition**
- [ ] retool-gui.exe
- [X] retool.py
- [ ] retool-gui.py

**Retool version**
v2.00.5

**Comment by muggsyd** [comment] 2023-06-01 01:54
Sorry, I forgot to mention, retool v2.00.5 had processed over 20 DATs successfully prior to his error. I run a script that find all dats and then runs retool.py against the found DATs using the switches above

**Comment by muggsyd** [comment] 2023-06-01 02:03
Removing that DAT from my workflow, it then failed on the following DAT
Arcade - PC-based (20230329-073558).dat
retool-testing  | Processing file 37/72
retool-testing  |
retool-testing  | * Reading DAT file: "/retool/dats/NoIntro/Arcade - PC-based (20230329-073558).dat"
retool-testing  | * Validating DAT file... done.
retool-testing  |
retool-testing  | |  DAT DETAILS
retool-testing  | |  Description: Arcade - PC-based
retool-testing  | |  Author/s: Hiccup
retool-testing  | |  URL: https://www.no-intro.org
retool-testing  | |  Version: 20230329-073558
retool-testing  | |  Numbered dat: No
retool-testing  |
* Processing DAT file... done
retool-testing  | * Applying category and user excludes...
retool-testing  |
retool-testing  | * Unexpected error:
retool-testing  |
retool-testing  |
retool-testing  | Traceback (most recent call last):
retool-testing  |   File "/retool/retool.py", line 297, in <module>
retool-testing  |     main()
retool-testing  |   File "/retool/retool.py", line 201, in main
retool-testing  |     processed_titles = IncludeExcludeTools.excludes(processed_titles, config, removes)
retool-testing  |   File "/retool/modules/titletools.py", line 186, in excludes
retool-testing  |     category_remove_name: str = f'{category.lower()}_removes'.replace(' ' , '_').replace('-', '_')
retool-testing  | UnboundLocalError: local variable 'category' referenced before assignment
retool-testing  |

**Comment by FidoFuz** [comment] 2023-06-02 00:13
confirmed same issue with the following dats:
Nintendo - Virtual Boy (20230405-120113).dat
Nintendo - Nintendo 3DS (Digital) (Deprecated) (20211116-092247).dat
Benesse - Pocket Challenge V2 (20230327-105840).dat

**Comment by FidoFuz** [comment] 2023-06-02 00:16
Think it's possibly due to some dats having the <category> tag in only some entries but not all entries and the code not correctly handling the scenario.

**Comment by unexpectedpanda** [comment] 2023-06-02 10:06
> Think it's possibly due to some dats having the category tag in only some entries but not all entries and the code not correctly handling the scenario.

That bit is handled fine. In this case, it's just a variable that wasn't set. It'll be fixed in the next release.

**Comment by unexpectedpanda** [comment] 2023-07-16 01:09
Fixed in v2.01.0.

**Closed by unexpectedpanda** 2023-07-16 01:09 UTC
Labels: bug
