### ISSUE TITLE
PS1: Tokimeki Memorial: Forever with You - Wrong revision

### ISSUE THREAD

**Issue by Keiyuu** [unexpectedpanda/retool#308] opened 2024-02-22 13:11 UTC
**Describe the bug**
Tokimeki Memorial - Forever with You (Japan) (Rev 4) | http://redump.org/disc/6764/
Tokimeki Memorial - Forever with You (Japan) (PlayStation the Best) | http://redump.org/disc/8876/

Retool is prioritizing Rev 4 when it should be picking the "PlayStation the Best" release.
As you can see on Redump, the Best has a newer EXE date than Rev 4.

**Operating system**
- [x] Windows 10 (older versions not supported)
- [ ] Ubuntu
- [ ] Other (please specify)

**Retool edition**
- [x] retool-gui.exe
- [ ] retool.py
- [ ] retool-gui.py

**Retool version**
2.02.1

**Comment by unexpectedpanda** [comment] 2024-02-22 21:40
This one has a few levels to it.

This might just be a file date, and not a guarantee that the game version is newer. Still, it's a fair assumption to expect a budget rerelease to have the newest version. No doubt there are exceptions, but a decent general rule to have.

I'll have to ask around to double check on the meaning. Retool doesn't currently take this field into account, so there are potential implications for other titles (not to mention `(Rerelease)` titles, which generally don't get selected as there's no indication of version there either).

PlayStation the Best titles are in the promote section of `internal-config.json`, so they do win a lot of the time. IIRC the original title wins here because it has a revision attached to it. This might ultimately mean I need to build separate handling for budget rereleases.

**Comment by Keiyuu** [comment] 2024-02-26 12:15
I can't speak for the actual content differences in this case. I only know that it was released in December 1997, a bit more than 2 years after the initial version.

But yeah, usually budget re-releases should have the newest revision in those instances when they differ.
I can think of a few more examples off the top of my head where they contain a newer version, although in those cases Redump tagged them as "Rev 1". And they also all have newer EXE dates.
Not sure why they didn't add any revision info in this particular case. Maybe an oversight?
But I personally don't even know how the revision info is established. When looking at the other versions with different revisions they all have the same EXE date (1995-08-31).

**Comment by unexpectedpanda** [comment] 2024-03-05 23:58
Confirmed the EXE date isn't a sign of a newer build. Still, looks like I need to implement a change that elevates budget titles before version checking is done, and if need be work out the exceptions along the way.

I found a [Reddit thread](https://www.reddit.com/r/Roms/comments/u47g61/what_are_the_rereleased_versions_of_ps1_games/) with a little more info on revisions and rereleases. Here's the relevant bit:

> Usually, the revision version it's printed on the disc/box art (rev 1, 2, 3, a, b, c, etc), but when there is no mention of it, the game will be tagged as rerelease.

> If didn't the rereleases didn't have any change in the code/data, the data hashes would match with the original game, without needing to store the rerelease data in a new entry.
>
> If a game has different data than the original version and has no revision version reference, then it's tagged as a rerelease, otherwise gets the revision version tag.

Looks like rereleases are still a mystery box, so for now I'll keep demoting those.

**Comment by unexpectedpanda** [comment] 2024-04-27 08:00
Fixed in v2.3.6.

**Closed by unexpectedpanda** 2024-04-27 08:00 UTC
Labels: enhancement
