### ISSUE TITLE
A few errors and suggestions on multiple No-Intro DAT

### ISSUE THREAD

**Issue by Jaylinx** [unexpectedpanda/retool#30] opened 2021-02-02 10:23 UTC
I'm using latest No-Intro DAT for 8-16 and handheld systems. All is ticked in "Exclusions". All is unticked in "Modes"

[screenshot archived]

I still have few (Beta) games in GBA, N64 and Genesis
I have many (Virtual Console) games left. For example, for NES, "Donkey Kong - Original Edition (USA) (Virtual Console)" shouldn't take place of "Donkey Kong (World) (Rev 1)" with my settings.

Do you think it would be possible to add option in "Exclusions" for (Add-on) (Manual) (SDK Build) and (Enhancement Build) which are not playable roms ?

Thanks for your software, this is very promising !

**Comment by unexpectedpanda** [comment] 2021-02-04 06:37
Thanks for the report -- I've removed the image from the issue for privacy, but I'll keep it locally until the issue is resolved.

## Betas
I can't replicate this when preproduction is selected in exclusions, or when all exclusions are selected. If I generate a dat for each of the affected systems in your screenshot with these options, then view them in a text editor, the titles that should be removed have been. This means your manager should remove the unneeded files when it finds them.

One thing I've seen with another user though is CLRMAMEPro not removing files it should. I don't know what triggers this, I've not experienced it personally, and it's hard to see the dat as the problem looking at its contents. But if you're using CLRMAMEPro, a potential workaround is to redownload it and extract it to a fresh folder as a separate install (don't overwrite your existing installation, start from scratch). If you're experiencing the same thing as the other user, the problem should be resolved.

At a pinch I'm guessing something has gotten corrupted in the CLRMAMEPro folder, but without being able to see the problem myself I don't know where to begin. If you _are_ using CLRMAMEPro, perhaps you could zip up your folder (minus the backups folder so the size is sane) and host it for me somewhere so I can download and see if I get the same result? I can't guarantee I can fix anything, but it might give us more data to raise a bug with Roman if the issue is on his side and not mine.

Of course this entire theory falls apart if you're using another manager :)

## Virtual Console (USA) vs original (World)
Region has a lot of priority in Retool. So if you have USA above World in your region list, then _Donkey Kong - Original Edition (USA) (Virtual Console)_ will be ranked above _Donkey Kong (World) (Rev 1)_, regardless of your ripped title settings. It's a bit more complicated to demote these titles cross-region, but I plan to look into it, as I agree this should be the behavior.

## Manuals, SDKs, Enhancement chips
No-Intro in theory can add infinite editions, and there's only so much room in the UI to add exclusions (not to mention I'm running out of command line switches, so I'll likely need to implement a `--exclude` flag that takes parameters to be able to manage things going forward). However, I think these are good ones, given that there's a decent amount of them. I'll look into adding them in future versions.

If you want to strip them out in the meantime, custom global filters can help you out.

**Comment by unexpectedpanda** [comment] 2021-03-01 09:28
Fixed in 0.88.

**Closed by unexpectedpanda** 2021-03-01 09:28 UTC
Labels: enhancement
