### ISSUE TITLE
Sega - Mega Drive - Genesis - Alien Soldier (Europe) is picked over NTSC versions

### ISSUE THREAD

**Issue by JPS-GER** [unexpectedpanda/retool#316] opened 2024-03-17 13:16 UTC
## Dat
Sega - Mega Drive - Genesis (20240316-023439).dat

## Issue
+ Alien Soldier (Europe)
  - Alien Soldier (Japan)
  - Alien Soldier (USA) (Virtual Console)
  - Alien Soldier (USA, Europe) (Switch Online)

Europe Version (PAL) is picked over USA or Japan version (NTSC) even if I select "Prefer Region over Language":

![image](https://github.com/unexpectedpanda/retool/assets/142158778/44ce72e6-2c9e-4978-abe6-a5a27fcf5d3a)

![image](https://github.com/unexpectedpanda/retool/assets/142158778/425215a5-e8ea-4ed9-8749-0a55ea4ae70f)

![image](https://github.com/unexpectedpanda/retool/assets/142158778/ed354714-d6d0-4eef-8b92-153c62118638)

**Comment by unexpectedpanda** [comment] 2024-03-17 21:04
This is because the USA versions are ripped from modern rereleases, which are demoted in favor of versions that were released for the original hardware.

This is working as intended. However it's raised that maybe some additional behavior is required in handling modern editions. Right now you can prefer releases for original hardware or modern rereleases -- perhaps there should just be a setting that means modern rereleases aren't treated specially at all.

**Comment by JPS-GER** [comment] 2024-03-18 20:03
This only explains the modern releases, but I also have Japan listed above Europe and it still picks the European version instead of the classic Japanese release.

I agree about the additional options. This also goes in the direction to prefer NTSC over PAL versions, as many people prefer 60Hz over 50Hz options. It's hard to do that with the current options.

**Comment by unexpectedpanda** [comment] 2024-03-18 20:37
Apologies, yesterday was a hard day and I missed that detail.

In this instance regions over languages is meant to work, I'll look into it and see what's getting in the way.

**Comment by unexpectedpanda** [comment] 2024-03-19 08:46
This was a little more complicated than expected, but it's been untangled and will be in the next release.

**Comment by unexpectedpanda** [comment] 2024-04-06 00:05
Fixed in v2.03.0.

**Closed by unexpectedpanda** 2024-04-06 00:05 UTC
Labels: bug, enhancement
