### ISSUE TITLE
[Beta Feedback]

### ISSUE THREAD

**Issue by rufotheone-fr** [unexpectedpanda/retool#242] opened 2023-03-11 08:39 UTC
Hi UP and congratulations for this v2!
The QoL improvements and the processing speed are really good.

I'm encountering several little issues:
- Redump dat, Retool is filtering both (Europe) & (Europe, Australia) tags;
- Redump dat, Retool is filtering both standalone & compilations (ex: Metal Slug 4/5 + Metal Slug Anthology)

**Comment by unexpectedpanda** [comment] 2023-03-11 10:09
Thanks for trying it out! I need a little more info though -- the word "filtering" is quite loaded here :)

Could you describe what happened, and what you expected to happen?

**Comment by Jaylinx** [comment] 2023-03-11 13:37
Overall design is good, system settings is a welcome addition.

I'm having a bug that I can't reproduce on V1. I have latest updates on Retool, latest No-Intro dats. I ticked everything on the exclusion tab. And even with everything ticked, I have plenty of "Pirate", "Homebrew" and "Aftermarket" roms on my created DAT. I don't understand !

**Comment by Nioh8** [comment] 2023-03-11 17:20
just to echo what @Jaylinx said, i am also still getting "pirate" roms in my dats after, also the option to "prefer licensed over unlicensed" seems to still give me a few homebrew in my nes and snes dat list.

**Comment by unexpectedpanda** [comment] 2023-03-11 21:20
> just to echo what @Jaylinx said, i am also still getting "pirate" roms in my dats after, also the option to "prefer licensed over unlicensed" seems to still give me a few homebrew in my nes and snes dat list.

That option only chooses a licensed alternative (potentially from another region) if it's available. It doesn't remove unlicensed ROMs. So if a homebrew version of a title is the only version, it'll be included. To strip out homebrew ROMs, you need to select **Unlicensed** in the **Exclusions** tab. Except...

> And even with everything ticked, I have plenty of "Pirate", "Homebrew" and "Aftermarket" roms on my created DATs.

Confirmed this is an issue. I suspect it might be the regex screwing up, but I'll need to dig.

**Comment by Nioh8** [comment] 2023-03-11 21:31
@unexpectedpanda thank you for explaning that, now I understand that option is working correctly after checking the list. 

All exclusions are ticked, but reading the last part of your respone there seems to be a issue there with the exclusions, the post report on my snes dat doesnt exclude any pirate roms, even when the exclusion is ticked, thanks

**Comment by unexpectedpanda** [comment] 2023-03-11 22:31
Okay, as of beta 4 aftermarket, homebrew, pirate, and unlicensed titles are removed again when you select **Unlicensed** in the **Exclusions** tab.

I think there's an opportunity to improve that in the GUI in the future, but for now this should work. Let me know how you go :)

**Comment by Nioh8** [comment] 2023-03-12 03:49
@unexpectedpanda working fine now thank you :)

**Comment by rufotheone-fr** [comment] 2023-03-12 09:09
> Thanks for trying it out! I need a little more info though -- the word "filtering" can have many meanings here :)
> 
> Could you describe what happened, and what you expected to happen? Make sure to include settings and title names if you think they're relevant.

Sorry for the delay.

When using those settings (everything else are default or blank), Retool sometimes keeps both (Europe) & (Europe, Australia). When writing this report, I've come to something: maybe Retool keeps both versions when there is something different (more languages, ver number, 
For example:
- redump wii => Disney-Pixar Cars 2 (Europe) (Fr,De,It) + Disney-Pixar Cars 2 (Europe, Australia) (En,Fr,Es,It,Nl) / Hot Wheels - Track Attack (Europe) (En,Fr,De,Es,It,Nl) + Hot Wheels - Track Attack (Europe, Australia) (En,Fr,De,Es,It,Nl) (Rev 1) / LEGO Star Wars III - The Clone Wars (Europe) (En,Fr,De,Es,It,Da) + LEGO Star Wars III - The Clone Wars (Europe, Australia) (En,Fr,De,Es,It,Da) (Rev 1) etc...

![Capture d’écran (112)](https://user-images.githubusercontent.com/57519964/224533871-f8d19f51-fe7d-496e-a5fe-13f44d3adbab.jpg)
![Capture d’écran (115)](https://user-images.githubusercontent.com/57519964/224533878-b4aa7e76-1dfe-4358-bdf7-3fa55a53903f.jpg)

**Comment by Jaylinx** [comment] 2023-03-12 18:40
Thanks for the update. 

I have another question ! So my settings are the one by default and everything ticked in exclusion tab. After scanning I have several roms that are selected in my DAT that seems a strange choice for me.

For example, in the NES DAT, a lot of roms have the (Namcot Collection) and (Castlevania Anniversary Collection) version selected over the parent ones. In SNES DAT , I have Trials of Mana from (Collection of Mana) selected over Seiken Densetsu 3. In GBA DAT, I have several (Pokemon Box) roms selected over originals. And many (Virtual Console) games selected in several other DATS.

Maybe I'm wrong but are these games considered as Aftermarket ? Even with "prefer licensed over unlicensed", I have the same results.

What is the status of games released on modern platforms after the lifespan of the original hardware ?

**Comment by unexpectedpanda** [comment] 2023-03-12 20:46
I guess they're technically aftermarket. They're usually not explicitly marked as such (although in this set Gaplus from the Namcot collection is).

Usually you'd get those modern platform rereleases if you turned on "Prefer titles ripped from modern rereleases". Sometimes, though, they turn up if they're the only English releases and English is high up in your language priority (even if you don't set a language priority, there's an inferred one from your region order). This looks to be the case here.

Looking at NES, all the _Namcot Collection_ titles that show up are _(World)_ titles that only have _(Japan)_ equivalents released during the console's lifespan. No-Intro has _Mappy_, _Galaxian_ et al listed as supporting Japanese only, despite this not being the case. Or at least, they historically did -- that database is no longer available for download (too much for the server, apparently), and I can't search Dat-O-Matic at the moment as that system is locked.

The right way to go about this I think is to get No-Intro to modify their entries to reflect the actual language used by the title (and then I have to get my hands on that database to turn it into metadata). Sometimes they've flagged titles where the language is not as you would expect in the filename, which helps too (for example, _Mappy (Japan) (En)_).

The same language selection is true of Trials of Mana on SNES. Pokemon box isn't recognized by Retool (it's not been defined in `internal-config.json`), so it's unlikely those titles are being selected over the original, you're more likely getting duplicates.

FWIW, you can check out why Retool is making the choices it is with the trace option:

![mappy](https://user-images.githubusercontent.com/15709984/224572013-a4397335-2e3d-4c4a-bc1f-3f2e9fa514d6.png)

**Comment by unexpectedpanda** [comment] 2023-03-12 22:17
> * redump wii => Disney-Pixar Cars 2 (Europe) (Fr,De,It) + Disney-Pixar Cars 2 (Europe, Australia) (En,Fr,Es,It,Nl) / Hot Wheels - Track Attack (Europe) (En,Fr,De,Es,It,Nl) + Hot Wheels - Track Attack (Europe, Australia) (En,Fr,De,Es,It,Nl) (Rev 1) / LEGO Star Wars III - The Clone Wars (Europe) (En,Fr,De,Es,It,Da) + LEGO Star Wars III - The Clone Wars (Europe, Australia) (En,Fr,De,Es,It,Da) (Rev 1) etc...

This is a pretty weird bug. I don't fully understand what's going on yet, but I do know that Retool is unassigning those titles as clones as it thinks the `(Europe)` and `(Europe, Australia)` titles have been set as clones of each other, which isn't allowed (it also claims they're all simultaneously clones of `Hot Wheels - Track Attack (Europe) (En,Fr,De,Es,It,Nl)`, which I suspect is just a logging error). This one's going to take more prodding than usual.

**Comment by unexpectedpanda** [comment] 2023-03-17 03:02
@rufotheone-fr, the Europe/Australia issue is fixed in beta 5.

**Comment by veritas5** [comment] 2023-03-17 23:36
> All the compilations processing is automatic... although damn NES got a _lot_ slower. It's time to fix that. I don't think beta 5 should have changed what you're seeing from beta 4, but I will check.
> 
> It is intended behavior for compilations to often outrank individual titles — the plan is to add a feature that preferences individual titles though (and it's likely to become the default). There are some cases where you don't want that (some compilations are an upgrade), but I'm yet to sort the mechanics of that.
> 
> You shouldn't be seeing the virtual name of the compilations though (a prefix of V followed by one of the individual titles)... that's a new one to me and a bit worrying. ~I can't replicate that -- what settings do you have?~
> 
> Looks like you're using RomCenter? Not that that changes anything, just curious.
> 
> Edit: I've replicated the virtual title issue. Looking into it now. Edit 2: Definite screw up on my behalf. I'll have beta 6 out shortly.

Hello,
First of all, thank you for creating this tool. It is very useful. I am having an issue with compilations and a few other random roms. It happens specifically with GBA, NDS, NES, SNES and Sega Master System No-Intro sets. I create 1G1R DATS with only English as a language and all of the exclusions applied. When I load any of these DAT files in CLRMAMEPRO I get the message "Issue:	Double description

Description will be changed to 'whatever the roms name is'"
For a bunch of the compilation games and a few other roms.

When I try to scan a set CLRMAMEPRO removes those roms and then shows them as missing.
![Screenshot (4)](https://user-images.githubusercontent.com/128193378/226069677-00439198-ed54-4181-99cc-0ea337678e61.png)
![Screenshot (5)](https://user-images.githubusercontent.com/128193378/226069690-b8002cea-e5ed-44a1-9165-f69c6f4ef22a.png)
![Screenshot (6)](https://user-images.githubusercontent.com/128193378/226069698-f52c4b15-9aa2-46c2-878d-f9c3276def07.png)

**Comment by unexpectedpanda** [comment] 2023-03-18 00:05
@veritas5 this is the same problem as Nioh, it's just manifesting differently in CLRMAMEPro. Working on the fix now. Thanks for the heads up :)

**Comment by unexpectedpanda** [comment] 2023-03-18 00:32
Fix is up in beta 6!

**Comment by rufotheone-fr** [comment] 2023-03-20 14:49
Currently testing my dats.

Some ideas:
- could it be possible to add a drag'n drop feature to the dat list?
- if you add some dats to the queue and launch and update for the clone lists, the update process will be started for every single dat (for example, if you add 5 dats, Retool will fetch 5 updates)

**Comment by unexpectedpanda** [comment] 2023-03-20 21:02
> could it be possible to add a drag'n drop feature to the dat list?

I'm guessing you mean treating it like a drop target, so you can drag files from explorer. I'm not sure if that would interfere with it its current behavior, I'd have to check it out.

> if you add some dats to the queue and launch and update for the clone lists, the update process will be started for every single dat (for example, if you add 5 dats, Retool will fetch 5 updates)

Currently the update just grabs all new clone lists/metadata. Are you wanting to reduce download time?

**Comment by unexpectedpanda** [comment] 2023-04-07 05:53
You can now drag and drop files into the DAT list.

**Comment by unexpectedpanda** [comment] 2023-04-07 06:00
I'm going to close this thread down for now -- new issues can go in their own threads :)

**Closed by unexpectedpanda** 2023-04-07 06:00 UTC
